name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      id: go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.6

    - name: SET GitHub ENV k8s version
      env:
        packageName: v1.19.16
      run: echo "packageName=${{ env.packageName }}" >> $GITHUB_ENV
    
    - name: Get github Env
      run: echo '${{ env.packageName }}'
       
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ env.packageName }}
    
    - name: modify cert time file
      run: |
        sed -i "s/365/365 * 99/" /home/runner/work/kubernetes/kubernetes/cmd/kubeadm/app/constants/constants.go
        sed -i "s/10)/99)/"  /home/runner/work/kubernetes/kubernetes/staging/src/k8s.io/client-go/util/cert/cert.go
    - name: Get modify file
      run: |
        find . -name constants.go |xargs cat |grep 365
        find . -name cert.go |xargs cat |grep 365d
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Get workpath
      run: pwd

    - name: Build kubeadm
      run: KUBE_GIT_TREE_STATE=clean make all WHAT=cmd/kubeadm GOFLAGS=-v

    - name: Get paGth
      run: find . -name kubeadm
    
    - name: Kubeadm version
      run: |
        chmod +x ./_output/local/bin/linux/amd64/kubeadm
        ./_output/local/bin/linux/amd64/kubeadm version
    - name: Package file dirname
      run: mkdir myki && cp ./_output/local/bin/linux/amd64/kubeadm myki

    - uses: actions/upload-artifact@v3
      with:
        name: kubeadm-${{ env.packageName }}
        path: myki
